import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa los estilos de FontAwesome
import { config } from '@fortawesome/fontawesome-svg-core'; // Importa la configuración de FontAwesome
config.autoAddCss = false; // Desactiva la auto-adición de CSS

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ing.Erick Garcia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
